### ISSUE TITLE
●	‘Stories’ page cannot be scrolled if the top section is too long (Chrome web browser)

### ISSUE THREAD

**Issue by jagus7** [CBIIT/nci-ctd2-dashboard#409] opened 2019-08-07 13:41 UTC
This is one of feedback given by Kwat (UCSD). I couldn't reproduce this. Please test this and close this issue if you don't see the same thing as Kwat.

**Comment by zhouji2013** [comment] 2019-09-25 21:24
I was not able to reproduce this, either.

**Comment by kcs3** [comment] 2019-10-09 20:24
Likely same issue as #411, some problem is periodically showing up in scrolling pages in the browser.

**Comment by kcs3** [comment] 2020-01-13 21:07
This is the same issue as #411, which has additional material, so will close this original report.

**Closed by kcs3** 2020-01-13 21:07 UTC
Labels: duplicate
