### ISSUE TITLE
no result returned, search seems not to end

### ISSUE THREAD

**Issue by kcs3** [CBIIT/nci-ctd2-dashboard#496] opened 2021-09-15 18:42 UTC
In testing #487, when the search phrase "mature B-cell non-Hodgkin's lymphoma" in quotes is searched, the search does not seem to terminate nor return any result.  searching for an invalid terms ends immediately, e.g. "pandemic".

**Comment by zhouji2013** [comment] 2021-09-21 18:37
When I tested in development and test instances, there is no issue. The result came back quickly; there are 61 subjects and 2 submissions in the results.

**Comment by zhouji2013** [comment] 2021-09-21 20:43
I reproduced the issue with a simpler example. Searching "Hodgkin's" on the production site gets 403; searching on the development site gets the result (one subject); searching "Hodgkin" works both on the production site and the development site. The "'s" part triggered the problem on the production site.

**Comment by zhouji2013** [comment] 2021-09-23 01:08
Another link that may be relevant https://forum.ait-pro.com/forums/topic/search-string-403-error/

**Comment by zhouji2013** [comment] 2021-09-30 14:37
Response from Yiwen: "The CBIIT app hosting team got back to me and this is what they found: the CTD2-Dashboard is configured with iTrust Siteminder configuration, and thus have to follow the security policy at CIT. The apostrophe character is potentially used for cross side scripting, and is thus blocked following the policy on the Siteminder server hosted by CIT. It looks like it can’t be fixed on the server side and we have to find a way to fix it in the code." It seems no matter how we modify the application, we have to break the original convention for stable URL of search view, which includes the search term as entered. Note that the URL encoding (%27 for ') does not help this issue.

**Comment by kcs3** [comment] 2021-11-12 20:08
Searching on "Hodgkin's" with the apostrophe (quotes not required) now works properly.  Verified on Columbia local test server.

**Comment by zhouji2013** [comment] 2021-12-17 17:24
The solution regarding apostrophe  (43867f8) does not work on the production site after being deployed as part of the latest release.

**Comment by kcs3** [comment] 2022-01-07 20:56
On the columbia test server, using the search string "Hodgkin's" without quotes, one result is quickly returned, follicular lymphoma.  

The only way to actually test this is, as before, to deploy on the NCI servers.

**Comment by arisf** [comment] 2022-06-02 15:10
The situation on the production server (release 5.3.0) is as follows:
* Searching for Hodgkin's (no quotes), correctly returns a single match, the term "follicular lymphoma"
* Searching for "Hodgkin's" (with quotes), returns no results.
* Searching for Hodgkin (both with and without quotes), correctly returns one result.

So only the second bullet is a problem - that search too should have matched "follicular lymphoma". I am sending this back to Zhou, to take another look. But at this point, I would say this is a minor issue. Let's fix if it is an easy fix. Otherwise, we can live with it.

**Comment by arisf** [comment] 2022-11-02 16:24
Confirmed fixed in production.

**Closed by arisf** 2022-11-02 16:24 UTC
Labels: bug, Released in v5.5.1
