### ISSUE TITLE
Disease context scrolling broken when selecting more roles than just disease

### ISSUE THREAD

**Issue by jagus7** [CBIIT/nci-ctd2-dashboard#411] opened 2019-08-07 14:15 UTC
I couldn't reproduce this, this is part of Kwat feedback.

**Comment by zhouji2013** [comment] 2019-09-25 21:25
I was not able to reproduce this, either.

**Comment by kcs3** [comment] 2019-10-09 20:14
I have seen what was probably reported several times now.  It probably does not have anything to do with selecting more roles per se, it is just that adding more rows in that way, and then needing to scroll to see them, revealed that scroll is not always working.  Sometimes one must refresh the page to get scrolling to work.  This is in Chrome.  We don't have any lead on what is wrong here...

**Comment by vdancik** [comment] 2019-10-10 15:35
The same happens in Firefox

**Comment by kcs3** [comment] 2020-01-13 20:18
Testing this on production release v3.40.  It is fully reproducible.  If a e.g. browse page is displayed, and then additional roles are added, so that the window needs to scroll, it looks like scrolling is just not being enabled, e.g. the window manager does not know that the page has changed size.

**Comment by kcs3** [comment] 2020-05-29 19:40
Verified that the fix works.  The problem was a little different than first described, as for some reason, selecting roles actually removed the scroll-bar from the window as it redrew.  Thus one could not scroll down to see things at the bottom of the page, although the page itself did not change size.

**Comment by kcs3** [comment] 2020-05-29 19:41
Zhou, any comment on what the actual problem was here?

**Comment by zhouji2013** [comment] 2020-05-29 23:06
This was a bug in the code handling the select button of the role selection dialog. It does not reset the background view properly after the dialog is closed.

**Comment by kcs3** [comment] 2020-07-01 19:18
Tested in production, closing issue.

**Closed by kcs3** 2020-07-01 19:18 UTC
Labels: Released in v4.10, bug
