### ISSUE TITLE
website - order by name-type priority

### ISSUE THREAD

**Issue by hermidalc** [CBIIT/nci-ctd2-dashboard#10] opened 2016-03-01 15:51 UTC
_Originally reported by_: @paulclemons

[1a] http://awabi.cbio.mskcc.org/ctd2-dashboard/#/subject/268648
in cell line pages can you  make the order of the displayed synonyms under 'Synonyms' and 'References' be the order of the name-type priority?

**Comment by hermidalc** [comment] 2016-03-01 15:51
*Original comment by*: @kcs3

Is this just a request to display synonyms and references in alphabetical order?

**Comment by hermidalc** [comment] 2016-03-01 15:51
*Original comment by*: @n1zea144

I will update the dashboard importer to save xrefs & synonyms in an order based on priority.

**Comment by kcs3** [comment] 2018-02-28 22:52
In looking at the subject page for SUDHL6, I see that the annotations are not in alphabetical order.

**Comment by kcs3** [comment] 2020-01-13 20:57
Not at all clear what was intended.  Closing issue.

**Comment by remontoire-pac** [comment] 2020-01-14 15:05
I see this is a pretty old issue ... can I help clarify it?
____________________________
Paul Clemons
Institute Scientist, Broad Institute
pclemons@broadinstitute.org
+1 (617) 359-9092
____________________________

**Comment by kcs3** [comment] 2020-01-14 16:39
Over to you, Paul.

**Comment by remontoire-pac** [comment] 2020-01-14 17:34
I think the original purpose of this ticket was to see if we can use the name-type-priority values (that are stored for cell lines in @vdancik internal database) to establish the display priority on these cell line subject pages. I suspect we are not importing that information, but I though we might not need to do so if the order or import of background data can be controlled and preserved.

**Comment by kcs3** [comment] 2020-01-14 17:49
"name-type-priority values" is undefined.  Do you want to pursue this?

**Comment by remontoire-pac** [comment] 2020-01-14 17:55
I think it's worth understanding (1) how difficult it would be to use this
additional information; (2) how much value it adds. The main point is to
make sure that the names/synonyms that people recognize are shown near the
top of a list of same. I think that the search capabilities we have
implemented since the ticket was created might have made this issue less
important. Every name we assign a cell line gets a priority within the list
of synonyms in the internal database that we keep synched between various
projects utilizing the CCLE cell lines.

**Comment by kcs3** [comment] 2020-01-14 17:59
OK I'll leave it with the Broad team for now.

**Comment by remontoire-pac** [comment] 2020-01-14 18:02
Vlado - do you think using our cell line name-type priorities in the
Dashboard is worthwhile? This is a very old ticket/issue that Leandro had
started to work on a few years ago.



____________________________
Paul Clemons
Institute Scientist, Broad Institute
pclemons@broadinstitute.org
+1 (617) 359-9092
____________________________

**Comment by vdancik** [comment] 2020-01-15 17:57
Files for cell-line background data contain name-priority information, however the priority is not loaded to the database as its schema does not support priority for synonyms.

**Comment by remontoire-pac** [comment] 2020-01-15 18:09
Understood--but the question is whether this is a change worth making. It
may not be due to the improvements of Search since last we visited this
issue with Leandro a few years ago.
____________________________
Paul Clemons
Institute Scientist, Broad Institute
pclemons@broadinstitute.org
+1 (617) 359-9092
____________________________

**Comment by vdancik** [comment] 2020-01-15 19:03
I think this is a low-priority issue

**Comment by remontoire-pac** [comment] 2020-01-15 19:39
OK - Ken you can go ahead and re-close it. I just wanted to make sure we
had this discussion before doing so.
____________________________
Paul Clemons
Institute Scientist, Broad Institute
pclemons@broadinstitute.org
+1 (617) 359-9092
____________________________

**Comment by kcs3** [comment] 2020-01-15 20:20
Closing issue.

**Closed by kcs3** 2020-01-15 20:20 UTC
Labels: enhancement, major, wontfix
